#!/usr/bin/env python3

import sys

from rqt_gui.main import Main


def add_arguments(parser):
    group = parser.add_argument_group("Options for crazyflies state_plugin")


main = Main()
sys.exit(
    main.main(
        sys.argv,
        standalone="rqt_crazyflies/StatePlugin",
        plugin_argument_provider=add_arguments,
    )
)
